/**
 * Planty API
 * API for communication between frontend, microcontroller and backend.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SensorConfigurationPayload { 
    /**
     * The minimum value used for scaling the raw sensor values.
     */
    humidityScalingFrom?: number;
    /**
     * The maximum value used for scaling the raw sensor values.
     */
    humidityScalingTo?: number;
    /**
     * Timeout in minutes for the sensor to sleep in between taking measurements
     */
    sleepTimeout?: number;
}

