/**
 * Planty API
 * API for communication between frontend, microcontroller and backend.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Sensor { 
    /**
     * The ID schema used for most database entities.
     */
    id?: number;
    /**
     * A name of an entity
     */
    name?: string;
    /**
     * A description of an entity
     */
    description?: string;
    /**
     * The minimum value used for scaling the raw sensor values.
     */
    humidityScalingFrom?: number;
    /**
     * The maximum value used for scaling the raw sensor values.
     */
    humidityScalingTo?: number;
    /**
     * A timestamp containing date and time.
     */
    lastCalibration?: Date;
    /**
     * Timeout in minutes for the sensor to sleep in between taking measurements
     */
    sleepTimeout?: number;
}

