version: '3.1'
services:
  db:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "quarkus"
      POSTGRES_PASSWORD: "V%TFwzTBFx#tM9bLxx#&YTpY6!5g@d"
      POSTGRES_DB: "planty"

